run:
  timeout: "5m"
  skip-files:
    - tools/tools.go
    - doc.go

linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - govet
    - gofumpt
    - whitespace
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - unconvert
    - errcheck
    - errorlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - tools/tools.go
    - doc.go
  exclude-rules:
    - path: _test\.go
      linters:
        - typecheck
linters-settings:
  goimports:
    local-prefixes: github.com/nitrictech
  govet:
    check-shadowing: false
  stylecheck:
    dot-import-whitelist:
      [
        "github.com/onsi/gomega",
        "github.com/onsi/ginkgo/v2",
        "github.com/onsi/gomega/gstruct",
      ]
